// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mean_directional_hausdorff_rcpp
double mean_directional_hausdorff_rcpp(Rcpp::NumericMatrix a, Rcpp::NumericMatrix b);
RcppExport SEXP _OsteoSort_mean_directional_hausdorff_rcpp(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_directional_hausdorff_rcpp(a, b));
    return rcpp_result_gen;
END_RCPP
}
// max_directional_hausdorff_rcpp
double max_directional_hausdorff_rcpp(Rcpp::NumericMatrix a, Rcpp::NumericMatrix b);
RcppExport SEXP _OsteoSort_max_directional_hausdorff_rcpp(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(max_directional_hausdorff_rcpp(a, b));
    return rcpp_result_gen;
END_RCPP
}
// dilated_directional_hausdorff_rcpp
double dilated_directional_hausdorff_rcpp(Rcpp::NumericMatrix a, Rcpp::NumericMatrix b);
RcppExport SEXP _OsteoSort_dilated_directional_hausdorff_rcpp(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(dilated_directional_hausdorff_rcpp(a, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OsteoSort_mean_directional_hausdorff_rcpp", (DL_FUNC) &_OsteoSort_mean_directional_hausdorff_rcpp, 2},
    {"_OsteoSort_max_directional_hausdorff_rcpp", (DL_FUNC) &_OsteoSort_max_directional_hausdorff_rcpp, 2},
    {"_OsteoSort_dilated_directional_hausdorff_rcpp", (DL_FUNC) &_OsteoSort_dilated_directional_hausdorff_rcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_OsteoSort(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
