# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

euclidean_distance_matrix_rcpp <- function(a, b) {
    .Call(`_OsteoSort_euclidean_distance_matrix_rcpp`, a, b)
}

max_directional_hausdorff_rcpp2 <- function(a, b) {
    .Call(`_OsteoSort_max_directional_hausdorff_rcpp2`, a, b)
}

mean_directional_hausdorff_rcpp <- function(a, b) {
    .Call(`_OsteoSort_mean_directional_hausdorff_rcpp`, a, b)
}

max_directional_hausdorff_rcpp <- function(a, b) {
    .Call(`_OsteoSort_max_directional_hausdorff_rcpp`, a, b)
}

dilated_directional_hausdorff_rcpp <- function(a, b) {
    .Call(`_OsteoSort_dilated_directional_hausdorff_rcpp`, a, b)
}

minimum_euclidean_distances_indices <- function(a, b) {
    .Call(`_OsteoSort_minimum_euclidean_distances_indices`, a, b)
}

random_means <- function(a, k) {
    .Call(`_OsteoSort_random_means`, a, k)
}

best_cluster <- function(a, m, k) {
    .Call(`_OsteoSort_best_cluster`, a, m, k)
}

