# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mean_directional_hausdorff_rcpp <- function(a, b) {
    .Call(`_OsteoSort_mean_directional_hausdorff_rcpp`, a, b)
}

max_directional_hausdorff_rcpp <- function(a, b) {
    .Call(`_OsteoSort_max_directional_hausdorff_rcpp`, a, b)
}

